trigger: 
  branches:
    include:
      - master      
  tags: 
    include:
      - 'v*'
  
pool:
  name: 'Dev4'

variables:
  - group: Paths
  - name: tag
    value: $[replace(variables['Build.SourceBranch'], 'refs/tags/v', '')]    
  - name: releaseBuild
    value: 'false'
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: versionMajor
    value: '1'
  - name: versionMinor
    value: '5'
  - name: versionPatch
    value: '0'

resources:
  repositories: 
    - repository: PipelineTemplate
      type: git
      name: Dev4_Libs\AzurePipelineTemplate

parameters:
  - name: publishToArtifact
    type: boolean
    default: true
      
jobs:
  - job: pipeline
    workspace:
      clean: all
    steps:         
      - template: make.yml@PipelineTemplate    
        parameters:
          ignoreBuild: false
          ignoreSource: true
          publishToArtifact: ${{ parameters.publishToArtifact }}
          generateNupkg: true
      - task: NuGetCommand@2
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
          nuGetFeedType: 'external'
          publishFeedCredentials: 'CGMHv2'