# Azure DevOps src-nupkg yaml template

trigger:
- master
- release
  


pool:
  name: 'default'

parameters:
  - name: ignoreBuild
    displayName: Ignore build process
    type: boolean
    default: false
    

variables:      
  - group: Environments
  - group: Versions
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Debug'
  - name: version
    value: '1.0.0.0'
  - name: updatorBuildDate
    value: ''
  - name: updatorVersionBuild
    value: ''
  - name: updatorVersionRev
    value: ''

resources:
  repositories: 
    - repository: PipelineTemplate
      type: git
      name: PipelineTemplate
jobs:
  - job: BuildNupkg     
    workspace:
      clean: all      
    steps:
      - template: azure-pipeline-build.yml@PipelineTemplate  
        parameters:
          id: 'johnny5581.Ancestor'
          ignoreBuild: ${{ parameters.ignoreBuild }}
      - template: azure-pipeline-artifact.yml@PipelineTemplate